### ISSUE TITLE
Instructions for generating fine-tuned training data

### ISSUE THREAD

**Issue by seriousCoolness** [recordcrash/alchemy-bot#1]
I was playing around with this, and I got the gpt-3.5 and gpt-4 versions of the commands working, but I'm having some trouble figuring out how to generate the training data to feed into a fine-tuned model, since I'm not familiar with jupyter. Is there any way that you could include the converted training data in the repo itself, or instructions on how to run the ipynb file? If you don't want to or can't, I completely understand. I just am very curious as to how a fine-tuned model compares to the standard gpt-3.5 version.

**Comment by recordcrash** [comment]
Here you go! https://gist.github.com/recordcrash/22d071e012c6d45d352367bbf32888cd 
I guess I'll add it to the repository too, actually, I removed some intermediate files like the big 105MB json, but the jsonl is just 2MB. Let me know if you need anything else. **REMEMBER IT COSTS 70 DOLLARS TO FINETUNE THIS THE DATA AS IS**. I used davinci, the most expensive finetunable model. Other models will be way cheaper, and you can try filtering the jsonl to reduce costs too, but you're on your own there.

PS: You no longer need this, but in case you want to run the notebook, I used PyCharm's native support combined with a virtual environment created from the requirements.txt file. It's a bit involved.
